baseURL: 'https://simonnie98.github.io'
title: Simon's Blog
theme: ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'A fast, clean Hugo theme'
homepage: 'https://simonnie98.github.io'
defaultContentLanguage: 'en'
googleAnalytics: G-xxx
paginate: 10
params:
  brand: HOME
  avatarURL: /images/messi.JPG
  author: Simon Nie
  authorDescription: I currently study as a Mphil student at CUHK. My research interests include storage systems and MLSys.
  info: My blog shares some daily notes.
  favicon: /images/messi.JPG
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
  darkModeTheme: data-dark-mode
  #darkModeTheme: icy-dark-mode
  comments:
    giscus:
      enable: true
#       <script src="https://giscus.app/client.js"
#         data-repo="SimonNie98/simonnie98.github.io"
#         data-repo-id="R_kgDOKPlNBA"
#         data-category-id="DIC_kwDOKPlNBM4CZGUZ"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="preferred_color_scheme"
#         data-lang="zh-CN"
#         crossorigin="anonymous"
#         async>
# </script>
      repo: SimonNie98/simonnie98.github.io
      repo_id: R_kgDOKPlNBA
      category: Announcements
      category_id: DIC_kwDOKPlNBM4CZGUZ
      mapping: pathname
      position: bottom
      lang: en # pick a language from https://github.com/giscus/giscus/tree/main/locales
    utteranc:
#     <script src="https://utteranc.es/client.js"
#         repo="SimonNie98/simonnie98.github.io"
#         issue-term="pathname"
#         label="Comment"
#         theme="preferred-color-scheme"
#         crossorigin="anonymous"
#         async>
# </script>
      enable: false
      repo: SimonNie98/simonnie98.github.io
      issueTerm: pathname
      label: Comment
  analytics:
    google:
      SiteVerificationTag: G-B6PYWWVSHL
    umami:
      enable: false
      website_id: xxx
      url: https://xxx
  guestbook:
    title: Guestbook
    description: Leave a comment below. It could be anything -- question, appreciation, information, or even humor.
  social:
    - name: GitHub
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/simonnie98/'
languages:
  en:
    languageName: EN
    menu:
      main:
        - name: Blog
          url: /blog
          weight: 1
        - name: Tags
          url: /tags
          weight: 2
        - name: Archive
          url: /archives
          weight: 3
        - name: Guestbook
          url: /guestbook
          weight: 4
        - name: Dashboard
          url: https://simonnie98.github.io
          weight: 5
  zh:
    languageName: 中
    author: Simon Nie
    authorDescription: 香港中文大学Mphil. 我的研究方向包括存储系统和MLSys.
    info: 欢迎来到我的博客,分享一些日常笔记。
    guestbook:
      title: 留言板
      description: 留下您的评论吧。
    menu:
      main:
        - name: 文章
          url: /blog
          weight: 1
        - name: 分类
          url: /tags
          weight: 2
        - name: 历史文章
          url: /archives
          weight: 3
        - name: 留言板
          url: /guestbook
          weight: 4
        - name: 网站统计
          url: https://simonnie98.github.io
          weight: 5
taxonomies:
  series: series
  tag: tags
